export const weatherType ={
    Thunderstorm:{
        icon:'zap',
        message:'It could get noisy!',
        background:'#',
    },
    Drizzle:{
        icon:'',
        message:'',
        background:'#',
    },
    Rain:{
        icon:'',
        message:'',
        background:'#',
    },
    Snow:{
        icon:'',
        message:'',
        background:'#',
    },
    Clear:{
        icon:'',
        message:'',
        background:'#',
    },
    Clouds:{
        icon:'',
        message:'',
        background:'#',
    },
    Haze:{
        icon:'',
        message:'',
        background:'#',
    },
    Mist:{
        icon:'',
        message:'',
        background:'#',
    },
}